# Generated by Django 3.2.15 on 2022-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_class', models.CharField(max_length=150)),
                ('teacher', models.CharField(max_length=100)),
                ('group', models.CharField(max_length=10)),
                ('auditorium', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('num_of_class', models.IntegerField()),
                ('date_of_class', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
